name: Trigger Workflow
on:
  push:
    branches:
      - '*'

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: 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" \
            https://api.github.com/repos/AlexTaynov/RepoForRun/dispatches \
            -d '{"event_type": "run-workflow"}'
