name: Trigger Workflow
on:
  push:
    branches:
      - '*'

env:
  TOKEN: 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

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          curl --silent --show-error --fail -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: ${{env.TOKEN}}" \
            https://api.github.com/repos/AlexTaynov/RepoForRun/dispatches \
            -d '{"event_type": "run-workflow"}'
