name: Trigger
on:
  repository_dispatch:
    types: [trigger]

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Repository B
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_B_TOKEN }}" \
            https://api.github.com/repos/AlexTaynov/RepoForRun/dispatches \
            -d '{"event_type": "run-workflow"}'